import {Injectable} from '@angular/core';

@Injectable()
export class OrderBookingProduct {
    cmpCode: string;
    distrCode: string;
    orderNo: string;
    customerRefNo: string;
    customerCode: string;
    customerShipCode: string;
    orderDt: string;
    remarks: string;
    latitude: string;
    longitude: string;
    startTime: string;
    endTime: string;
    orderStatus: string;
    totalGrossValue = 0;
    totalDiscount = 0;
    totalTax = 0;
    totalOrderValue = 0;
    prodCode: string;
    prodName: string;
    prodBatchCode: string;
    orderQty = 0;
    servicedQty = 0;
    uomCode: string;
    inputStr: string;
    mrp: any;
    sellRate: any;
    sellRateWithTax: any;
    actualSellRate: any;
    grossValue = 0;
    schAmt = 0;
    taxAmt = 0;
    taxCode: string;
    cgstPerc = 0;
    cgstAmt = 0;
    sgstPerc = 0;
    sgstAmt = 0;
    ugstPerc = 0;
    ugstAmt = 0;
    igstPerc = 0;
    igstAmt = 0;
    orderValue = 0;
    prodType: string;
    brandCode: string;
    brandName: string;
    uomList = {};
    uomDisplayList = [];
    baseUOM: string;
    defaultUOM: string;
    favorite: string;
    soq: any;
    distrStateCode: string;
    customerStateCode: string;
    unionTerritoryFlag: string;
    qty: any;
    image: any;
    schemeAvailable: boolean;
    schemeArr: [];
    schemeSuggestion: boolean;
    schemeSuggestionText: string;
    freeSchemeText: string;
    schemeAmtText: string;
    convertedSchemeQty = 0;
    freeSchemeProduct = [];
    schemeAmtDetail = [];
    showSchemeCard = false;
    selectedScheme: any;
    showPrevNavigation = false;
    showNextNavigation = false;
    mappedSchemePos = 0;
    slabArr = [];
    convertedSchemeWeight = 0;
    prodNetWgt = 0;
    prodWgtType: string;
    orderLevelSchAmt = 0;
    enableProduct: string;
    prodColor: string;
    schemeDescription: string;
    schemeNotification: string;
    schemeCount: string;
    borderColor: string;
    slabProduct = [];
}
