package com.botree.reportcompute;

/**
 * Class contains constants.
 * @author SamiranBiswas.
 */
public final class TransactionStringConstants {

    /** CMPCODE. */
    public static final String CMPCODE = "TGBL";
    /** DISTRCODE. */
    public static final String DISTRCODE = "0000100711";
    /** LOGINCODE. */
    public static final String LOGINCODE = "8973690321";
    /** ORDER_BOOKING_DETAILS_ORDERNO. */
    public static final String ORDER_BOOKING_DETAILS_ORDERNO = "ORDER100";
    /** ORDER_BOOKING_DETAILS_PRODCODE. */
    public static final String ORDER_BOOKING_DETAILS_PRODCODE = "TT178";
    /** ORDER_BOOKING_DETAILS_PRODNAME. */
    public static final String ORDER_BOOKING_DETAILS_PRODNAME = "Tata Tea Elaichi Chai PP 250g-NZ";
    /** ORDER_BOOKING_DETAILS_PRODBATCHCODE. */
    public static final String ORDER_BOOKING_DETAILS_PRODBATCHCODE = "SA06-06-20";
    /** DISTRCODE. */
    public static final Integer ORDER_BOOKING_DETAILS_ORDERQTY = 2;
    /** ORDER_BOOKING_DETAILS_ORDERQTY. */
    public static final Integer ORDER_BOOKING_DETAILS_SERVICEDQTY = 0;
    /** ORDER_BOOKING_DETAILS_UOMCODE. */
    public static final String ORDER_BOOKING_DETAILS_UOMCODE = "PAC";
    /** ORDER_BOOKING_DETAILS_INPUTSTR. */
    public static final String ORDER_BOOKING_DETAILS_INPUTSTR = "2PAC";
    /** ORDER_BOOKING_DETAILS_SELLRATE. */
    public static final Double ORDER_BOOKING_DETAILS_SELLRATE = 57.620000;
    /** ORDER_BOOKING_DETAILS_ACTUALSELLRATE. */
    public static final Double ORDER_BOOKING_DETAILS_ACTUALSELLRATE = 57.620000;
    /** ORDER_BOOKING_DETAILS_GROSSVALUE. */
    public static final Double ORDER_BOOKING_DETAILS_GROSSVALUE = 115.240000;
    /** ORDER_BOOKING_DETAILS_SCHAMT. */
    public static final Double ORDER_BOOKING_DETAILS_SCHAMT = 0.000000;
    /** ORDER_BOOKING_DETAILS_TAXAMT. */
    public static final Double ORDER_BOOKING_DETAILS_TAXAMT = 5.762000;
    /** ORDER_BOOKING_DETAILS_TAXCODE. */
    public static final String ORDER_BOOKING_DETAILS_TAXCODE = "09";
    /** ORDER_BOOKING_DETAILS_CGSTAMT. */
    public static final Double ORDER_BOOKING_DETAILS_CGSTAMT = 2.881000;
    /** ORDER_BOOKING_DETAILS_CGSTPERC. */
    public static final Double ORDER_BOOKING_DETAILS_CGSTPERC = 2.881000;
    /** ORDER_BOOKING_DETAILS_SGSTAMT. */
    public static final Double ORDER_BOOKING_DETAILS_SGSTAMT = 2.881000;
    /** ORDER_BOOKING_DETAILS_SGSTPERC. */
    public static final Double ORDER_BOOKING_DETAILS_SGSTPERC = 2.881000;
    /** ORDER_BOOKING_DETAILS_UGSTAMT. */
    public static final Double ORDER_BOOKING_DETAILS_UGSTAMT = 0.000000;
    /** ORDER_BOOKING_DETAILS_UGSTPERC. */
    public static final Double ORDER_BOOKING_DETAILS_UGSTPERC = 0.000000;
    /** DISTRCODE. */
    public static final Double ORDER_BOOKING_DETAILS_IGSTAMT = 0.000000;
    /** ORDER_BOOKING_DETAILS_IGSTAMT. */
    public static final Double ORDER_BOOKING_DETAILS_IGSTPERC = 0.000000;
    /** ORDER_BOOKING_DETAILS_ORDERVALUE. */
    public static final Double ORDER_BOOKING_DETAILS_ORDERVALUE = 121.002000;
    /** ORDER_BOOKING_DETAILS_PRODTYPE. */
    public static final String ORDER_BOOKING_DETAILS_PRODTYPE = "N";
    /** UPLOADFLAG. */
    public static final String UPLOADFLAG = "N";

    /** ORDERBOOKINGSERVICEDETAILS_ORDERNO. */
    public static final String ORDERBOOKINGSERVICEDETAILS_ORDERNO = "ORDER100";
    /** ORDERBOOKINGSERVICEDETAILS_INVOICENO. */
    public static final String ORDERBOOKINGSERVICEDETAILS_INVOICENO = "INVOICE100";
    /** ORDERBOOKINGSERVICEDETAILS_PRODNAME. */
    public static final String ORDERBOOKINGSERVICEDETAILS_PRODNAME = "TATA tea";
    /** ORDERBOOKINGSERVICEDETAILS_PRODCODE. */
    public static final String ORDERBOOKINGSERVICEDETAILS_PRODCODE = "PRODCODE100";
    /** ORDERBOOKINGSERVICEDETAILS_PRODBATCHCODE. */
    public static final String ORDERBOOKINGSERVICEDETAILS_PRODBATCHCODE = "PRODBCODE100";
    /** ORDERBOOKINGSERVICEDETAILS_SELLRATE. */
    public static final Double ORDERBOOKINGSERVICEDETAILS_SELLRATE = 43.87;
    /** ORDERBOOKINGSERVICEDETAILS_SOQQTY. */
    public static final Integer ORDERBOOKINGSERVICEDETAILS_SOQQTY = 3;
    /** ORDERBOOKINGSERVICEDETAILS_SOQVALUE. */
    public static final Double ORDERBOOKINGSERVICEDETAILS_SOQVALUE = 4.5;
    /** ORDERBOOKINGSERVICEDETAILS_ORDERQTY. */
    public static final Integer ORDERBOOKINGSERVICEDETAILS_ORDERQTY = 6;
    /** ORDERBOOKINGSERVICEDETAILS_ORDERVALUE. */
    public static final Double ORDERBOOKINGSERVICEDETAILS_ORDERVALUE = 45.98;
    /** ORDERBOOKINGSERVICEDETAILS_SERVICEDQTY. */
    public static final Integer ORDERBOOKINGSERVICEDETAILS_SERVICEDQTY = 2;
    /** ORDERBOOKINGSERVICEDETAILS_SERVICEDVALUE. */
    public static final Double ORDERBOOKINGSERVICEDETAILS_SERVICEDVALUE = 121.002000;

    /** ORDERBOOKINGSCHEMEDETAILS_ORDERNO. */
    public static final String ORDERBOOKINGSCHEMEDETAILS_ORDERNO = "UE03812020072700010";
    /** ORDERBOOKINGSCHEMEDETAILS_SCHEMECODE. */
    public static final String ORDERBOOKINGSCHEMEDETAILS_SCHEMECODE = "SCHFMC165480";
    /** ORDERBOOKINGSCHEMEDETAILS_SLABNO. */
    public static final String ORDERBOOKINGSCHEMEDETAILS_SLABNO = "1";
    /** ORDERBOOKINGSCHEMEDETAILS_FREEPRODCODE. */
    public static final String ORDERBOOKINGSCHEMEDETAILS_FREEPRODCODE = "TA034";
    /** ORDERBOOKINGSCHEMEDETAILS_FREEQTY. */
    public static final int ORDERBOOKINGSCHEMEDETAILS_FREEQTY = 1;

    /** ORDERBOOKINGSCHEMEPRODUCTRULE_SCHEMECODE. */
    public static final String ORDERBOOKINGSCHEMEPRODUCTRULE_SCHEMECODE = "SCHFMC165481";
    /** ORDERBOOKINGSCHEMEPRODUCTRULE_SLABNO. */
    public static final String ORDERBOOKINGSCHEMEPRODUCTRULE_SLABNO = "1";
    /** ORDERBOOKINGSCHEMEPRODUCTRULE_PRODCODE. */
    public static final String ORDERBOOKINGSCHEMEPRODUCTRULE_PRODCODE = "TA035";
    /** ORDERBOOKINGSCHEMEPRODUCTRULE_DISCPERC. */
    public static final Double ORDERBOOKINGSCHEMEPRODUCTRULE_DISCPERC = 0.000000;
    /** ORDERBOOKINGSCHEMEPRODUCTRULE_DISCAMT. */
    public static final Double ORDERBOOKINGSCHEMEPRODUCTRULE_DISCAMT = 5.000000;
    /** ORDERBOOKINGSCHEMEPRODUCTRULE_ORDERNO. */
    public static final String ORDERBOOKINGSCHEMEPRODUCTRULE_ORDERNO = "UE03812020072700005";

    /** ORDERBOOKINGHEADERENTITY_TOTALORDERVALUE. */
    public static final Double ORDERBOOKINGHEADERENTITY_TOTALORDERVALUE = 590.320000;
    /** ORDERBOOKINGHEADERENTITY_TOTALTAX. */
    public static final Double ORDERBOOKINGHEADERENTITY_TOTALTAX = 28.110000;
    /** ORDERBOOKINGHEADERENTITY_TOTALDISCOUNT. */
    public static final Double ORDERBOOKINGHEADERENTITY_TOTALDISCOUNT = 0.000000;
    /** ORDERBOOKINGHEADERENTITY_TOTALGROSSVALUE. */
    public static final Double ORDERBOOKINGHEADERENTITY_TOTALGROSSVALUE = 562.210000;
    /** ORDERBOOKINGHEADERENTITY_ORDERSTATUS. */
    public static final String ORDERBOOKINGHEADERENTITY_ORDERSTATUS = "P";
    /** ORDERBOOKINGHEADERENTITY_LONGITUDE. */
    public static final String ORDERBOOKINGHEADERENTITY_LONGITUDE = "28.6000964";
    /** ORDERBOOKINGHEADERENTITY_LATITUDE. */
    public static final String ORDERBOOKINGHEADERENTITY_LATITUDE = "28.6000964";
    /** ORDERBOOKINGHEADERENTITY_REMARKS. */
    public static final String ORDERBOOKINGHEADERENTITY_REMARKS = "Order Placed in Retailer SSFA";
    /** ORDERBOOKINGHEADERENTITY_CUSTOMERCODE. */
    public static final String ORDERBOOKINGHEADERENTITY_CUSTOMERCODE = "UE0381";
    /** ORDERBOOKINGHEADERENTITY_CUSTOMERREFNO. */
    public static final String ORDERBOOKINGHEADERENTITY_CUSTOMERREFNO = "2020072800015";
    /** ORDERBOOKINGHEADERENTITY_SETORDERNO. */
    public static final String ORDERBOOKINGHEADERENTITY_ORDERNO = "UE03812020072800015";
    /** ORDERBOOKINGHEADERENTITY_CUSTOMERSHIPCODE. */
    public static final String ORDERBOOKINGHEADERENTITY_CUSTOMERSHIPCODE = "CSAFMC1669794";
    /** USERNAME. */
    public static final String USERNAME = "LAXMI STORE";
    /** USERSTATUS. */
    public static final String USERSTATUS = "P";

    /** UPDATE_QUEARY. */
    public static final String UPDATE_QUEARY = " UPDATE useractivation\n"
            + "        SET MsgRequestDt = NOW(),\n"
            + "            UserStatus   = 'P',\n"
            + "            UploadFlag   = 'N',\n"
            + "            ModDt        = NOW()\n"
            + "        WHERE LoginCode = ?";



    /**
     * default constructor.
     */
    private TransactionStringConstants() {
    }

}
