-- master
-- company
INSERT INTO externalprocessdetail
(CmpCode,
InterDBProcess,
ProcessType,
ProcessEnable,
InterDBQuery,
InterDBUpdateQuery,
Entity,
ProcessSequence,
ProcessStatus,
StartDate,
EndDate,
DistributorWise,
Incremental,
MaxChangeNo,
Intervals)
VALUES
('AMUL',
'company',
'M',
'Y',
'SELECT CmpCode,
       CmpName,
       CmpAddr1,
       CmpAddr2,
       CmpAddr3,
       City,
       State,
       Country,
       PostalCode,
       ''N'' AS UploadFlag,
       NOW() AS ModDt
FROM company',
'',
'com.botree.interdbentity.model.CompanyEntity',
1,
null,
null,
null,
'N',
'N',
0,
'24HRS');

-- customer
INSERT INTO externalprocessdetail
(CmpCode,
InterDBProcess,
ProcessType,
ProcessEnable,
InterDBQuery,
InterDBUpdateQuery,
Entity,
ProcessSequence,
ProcessStatus,
StartDate,
EndDate,
DistributorWise,
Incremental,
MaxChangeNo,
Intervals)
VALUES
('AMUL',
'customer',
'M',
'Y',
'SELECT CmpCode,
    DistrCode,
    CustomerCode,
    CustomerName,
    MobileNo,
    PinCode,
    PhoneNo,
    ContactPerson,
    EmailID,
    RetailerStatus,
    FssaiNo,
    CreditBills,
    CreditDays,
    CreditLimit,
    CashDiscPerc,
    ChannelCode,
    SubChannelCode,
    GroupCode,
    ClassCode,
    StoreType,
    ParentCustomerCode,
    Latitude,
    Longitude,
    CustomerType,
    GSTTinNo,
    PanNo,
    ApprovalStatus,
    ''N'' AS UploadFlag,
    NOW() AS ModDt
FROM customer
WHERE DistrCode IN (:ids)',
'',
'com.botree.interdbentity.model.CustomerEntity',
2,
null,
null,
null,
'Y',
'N',
0,
'24HRS');

-- customershipaddress
INSERT INTO externalprocessdetail
(CmpCode,
InterDBProcess,
ProcessType,
ProcessEnable,
InterDBQuery,
InterDBUpdateQuery,
Entity,
ProcessSequence,
ProcessStatus,
StartDate,
EndDate,
DistributorWise,
Incremental,
MaxChangeNo,
Intervals)
VALUES
('AMUL',
'customershipaddress',
'M',
'Y',
'SELECT CmpCode,
       DistrCode,
       CustomerCode,
       CustomerShipCode,
       CustomerShipAddr1,
       CustomerShipAddr2,
       CustomerShipAddr3,
       City,
       GSTStateCode,
       PhoneNo,
       DefaultShipAddr,
       ''N'' AS UploadFlag,
       NOW() AS ModDt
FROM customershipaddress
WHERE DistrCode IN (:ids)',
'',
'com.botree.interdbentity.model.CustomerShipAddressEntity',
3,
null,
null,
null,
'Y',
'N',
0,
'24HRS');

-- distributor
INSERT INTO externalprocessdetail
(CmpCode,
InterDBProcess,
ProcessType,
ProcessEnable,
InterDBQuery,
InterDBUpdateQuery,
Entity,
ProcessSequence,
ProcessStatus,
StartDate,
EndDate,
DistributorWise,
Incremental,
MaxChangeNo,
Intervals)
VALUES
('AMUL',
'distributor',
'M',
'Y',
'SELECT CmpCode,
       DistrCode,
       DistrName,
       DistrAddr1,
       DistrAddr2,
       DistrAddr3,
       PinCode,
       PhoneNo,
       MobileNo,
       ContactPerson,
       EmailID,
       GSTStateCode,
       DayOff,
       DistrStatus,
       ''Y'' AS loadStockProd,
       ''N'' AS UploadFlag,
       NOW() AS ModDt
FROM distributor
WHERE DistrCode IN (:ids)',
'',
'com.botree.interdbentity.model.DistributorEntity',
4,
null,
null,
null,
'Y',
'N',
0,
'24HRS');

-- distributorlobmapping
INSERT INTO externalprocessdetail
(CmpCode,
InterDBProcess,
ProcessType,
ProcessEnable,
InterDBQuery,
InterDBUpdateQuery,
Entity,
ProcessSequence,
ProcessStatus,
StartDate,
EndDate,
DistributorWise,
Incremental,
MaxChangeNo,
Intervals)
VALUES
('AMUL',
'distributorlobmapping',
'M',
'Y',
'SELECT CmpCode,
       DistrCode,
       LOBCode,
       ''N'' AS UploadFlag,
       NOW() AS ModDt
FROM distributorlobmapping
WHERE DistrCode IN (:ids)',
'',
'com.botree.interdbentity.model.DistributorLOBMappingEntity',
5,
null,
null,
null,
'Y',
'N',
0,
'24HRS');

-- lobmaster
INSERT INTO externalprocessdetail
(CmpCode,
InterDBProcess,
ProcessType,
ProcessEnable,
InterDBQuery,
InterDBUpdateQuery,
Entity,
ProcessSequence,
ProcessStatus,
StartDate,
EndDate,
DistributorWise,
Incremental,
MaxChangeNo,
Intervals)
VALUES
('AMUL',
'lobmaster',
'M',
'Y',
'SELECT CmpCode,
       LOBCode,
       LOBName,
       ''N'' AS UploadFlag,
       NOW() AS ModDt
FROM lobmaster',
'',
'com.botree.interdbentity.model.LOBMasterEntity',
6,
null,
null,
null,
'N',
'N',
0,
'24HRS');

-- producthierlevel
INSERT INTO externalprocessdetail
(CmpCode,
InterDBProcess,
ProcessType,
ProcessEnable,
InterDBQuery,
InterDBUpdateQuery,
Entity,
ProcessSequence,
ProcessStatus,
StartDate,
EndDate,
DistributorWise,
Incremental,
MaxChangeNo,
Intervals)
VALUES
('AMUL',
'producthierlevel',
'M',
'Y',
'SELECT CmpCode,
       ProdHierLvlCode,
       ProdHierLvlName,
       ''N'' AS UploadFlag,
       NOW() AS ModDt
FROM producthierlevel',
'',
'com.botree.interdbentity.model.ProductHierLevelEntity',
7,
null,
null,
null,
'N',
'N',
0,
'24HRS');

-- producthiervalue
INSERT INTO externalprocessdetail
(CmpCode,
InterDBProcess,
ProcessType,
ProcessEnable,
InterDBQuery,
InterDBUpdateQuery,
Entity,
ProcessSequence,
ProcessStatus,
StartDate,
EndDate,
DistributorWise,
Incremental,
MaxChangeNo,
Intervals)
VALUES
('AMUL',
'producthiervalue',
'M',
'Y',
'SELECT CmpCode,
       ProdHierLvlCode,
       ProdHierValCode,
       ProdHierValName,
       ParentCode,
       ''N'' AS UploadFlag,
       NOW() AS ModDt
FROM producthiervalue',
'',
'com.botree.interdbentity.model.ProductHierValueEntity',
8,
null,
null,
null,
'N',
'N',
0,
'24HRS');

-- product
INSERT INTO externalprocessdetail
(CmpCode,
InterDBProcess,
ProcessType,
ProcessEnable,
InterDBQuery,
InterDBUpdateQuery,
Entity,
ProcessSequence,
ProcessStatus,
StartDate,
EndDate,
DistributorWise,
Incremental,
MaxChangeNo,
Intervals)
VALUES
('AMUL',
'product',
'M',
'Y',
'SELECT p.CmpCode,
       p.ProdCode,
       p.ProdName,
       p.ProdShortName,
       p.ProdStatus,
       p.ProdType,
       p.ProdShelfLife,
       p.ProdNetWgt,
       p.ProdWgtType,
       p.LOBDivisionCode AS LOBCode,
       l.LOBName         AS LOBName,
       p.HSNCode,
       p.HSNName,
       p.ProductHierPathCode,
       p.ProductHierPathName,
       ''N''             AS UploadFlag,
       NOW()             AS ModDt
FROM product p
         INNER JOIN lobmaster l
                    ON p.CmpCode = l.CmpCode
                        AND p.LOBDivisionCode = l.LOBCode',
'',
'com.botree.interdbentity.model.ProductEntity',
9,
null,
null,
null,
'N',
'N',
0,
'24HRS');

-- productbatch
INSERT INTO externalprocessdetail
(CmpCode,
InterDBProcess,
ProcessType,
ProcessEnable,
InterDBQuery,
InterDBUpdateQuery,
Entity,
ProcessSequence,
ProcessStatus,
StartDate,
EndDate,
DistributorWise,
Incremental,
MaxChangeNo,
Intervals)
VALUES
('AMUL',
'productbatch',
'M',
'Y',
'SELECT CmpCode,
       DistrCode AS BatchLevel,
       ProdCode,
       ProdBatchCode,
       MRP,
       SellRate,
       SellRateWithTax,
       ManfDate,
       ExpiryDate,
       LatestBatch,
       ''N''     AS GeoLevelBatch,
       ''N''     AS UploadFlag,
       NOW()     AS ModDt
FROM productbatch',
'',
'com.botree.interdbentity.model.ProductBatchEntity',
10,
null,
null,
null,
'N',
'N',
0,
'24HRS');

-- productuom
INSERT INTO externalprocessdetail
(CmpCode,
InterDBProcess,
ProcessType,
ProcessEnable,
InterDBQuery,
InterDBUpdateQuery,
Entity,
ProcessSequence,
ProcessStatus,
StartDate,
EndDate,
DistributorWise,
Incremental,
MaxChangeNo,
Intervals)
VALUES
('AMUL',
'productuom',
'M',
'Y',
'SELECT CmpCode,
       ProdCode,
       UOMCode,
       UOMDescription,
       UomConvFactor,
       BaseUOM,
       DefaultUOM,
       ''N'' AS UploadFlag,
       NOW() AS ModDt
FROM productuom',
'',
'com.botree.interdbentity.model.ProductUomEntity',
11,
null,
null,
null,
'N',
'N',
0,
'24HRS');

-- retailercategory
INSERT INTO externalprocessdetail
(CmpCode,
InterDBProcess,
ProcessType,
ProcessEnable,
InterDBQuery,
InterDBUpdateQuery,
Entity,
ProcessSequence,
ProcessStatus,
StartDate,
EndDate,
DistributorWise,
Incremental,
MaxChangeNo,
Intervals)
VALUES
('AMUL',
'retailercategory',
'M',
'Y',
'SELECT CmpCode,
       ChannelCode,
       ChannelName,
       SubChannelCode,
       SubChannelName,
       GroupCode,
       GroupName,
       ClassCode,
       ClassName,
       ''N'' AS UploadFlag,
       NOW() AS ModDt
FROM retailercategory',
'',
'com.botree.interdbentity.model.RetailerCategoryEntity',
12,
null,
null,
null,
'N',
'N',
0,
'24HRS');

-- taxstructure
INSERT INTO externalprocessdetail
(CmpCode,
InterDBProcess,
ProcessType,
ProcessEnable,
InterDBQuery,
InterDBUpdateQuery,
Entity,
ProcessSequence,
ProcessStatus,
StartDate,
EndDate,
DistributorWise,
Incremental,
MaxChangeNo,
Intervals)
VALUES
('AMUL',
'taxstructure',
'M',
'Y',
'SELECT CmpCode,
       TaxStateCode,
       ProdCode,
       CGST,
       SGST,
       IGST,
       CESS,
       AdditionalTax,
       ''N'' AS UploadFlag,
       NOW() AS ModDt
FROM taxstructure',
'',
'com.botree.interdbentity.model.TaxStructureEntity',
13,
null,
null,
null,
'N',
'N',
0,
'24HRS');

-- distributorstock
INSERT INTO externalprocessdetail
(CmpCode,
InterDBProcess,
ProcessType,
ProcessEnable,
InterDBQuery,
InterDBUpdateQuery,
Entity,
ProcessSequence,
ProcessStatus,
StartDate,
EndDate,
DistributorWise,
Incremental,
MaxChangeNo,
Intervals)
VALUES
('AMUL',
'distributorstock',
'M',
'Y',
'SELECT temp.CmpCode,
       temp.DistrCode,
       GROUP_CONCAT(temp.ProdCode, ''^'', temp.SaleableQty) AS saleableStock,
       ''N'' AS UploadFlag,
       NOW() AS ModDt
FROM (SELECT CmpCode,
             DistrCode,
             ProdCode,
             SUM(SaleableQty) AS SaleableQty
      FROM stockonhand
      WHERE DistrCode IN (:ids)
	AND SaleableQty > 0
      GROUP BY CmpCode, DistrCode, ProdCode) AS temp
GROUP BY temp.CmpCode, temp.DistrCode',
'',
'com.botree.interdbentity.model.DistributorStockEntity',
14,
null,
null,
null,
'Y',
'N',
0,
'24HRS');

-- customerstock
INSERT INTO externalprocessdetail
(CmpCode,
InterDBProcess,
ProcessType,
ProcessEnable,
InterDBQuery,
InterDBUpdateQuery,
Entity,
ProcessSequence,
ProcessStatus,
StartDate,
EndDate,
DistributorWise,
Incremental,
MaxChangeNo,
Intervals)
VALUES
('AMUL',
'customerstock',
'M',
'Y',
'SELECT CmpCode,
       DistrCode,
       CustomerCode,
       GROUP_CONCAT(ProdCode, ''^'', 0, ''^'', PPQ) AS Stock,
       ''N'' AS UploadFlag,
       NOW() AS ModDt
FROM (SELECT CmpCode,
             DistrCode,
             CustomerCode,
             ProdCode,
             REPLACE(GROUP_CONCAT(InvoiceQty), '','', ''~'') AS PPQ
      FROM (SELECT @row_number := CASE
                                      WHEN @str = ID THEN @row_number + 1
                                      ELSE 1
          END AS row_number,
            @str:=ID AS str,
            CmpCode,
            DistrCode,
            CustomerCode,
            ProdCode,
            InvoiceDt,
            InvoiceQty
            FROM
                (SELECT
                CONCAT(ih.CmpCode, ih.DistrCode, ih.CustomerCode, id.ProdCode) AS ID,
                ih.CmpCode,
                ih.DistrCode,
                ih.CustomerCode,
                id.ProdCode,
                ih.InvoiceDt,
                SUM(id.InvoiceQty1) AS InvoiceQty
                FROM
                invoiceheader ih
                INNER JOIN invoicedetails id
                ON ih.CmpCode = id.CmpCode
                AND ih.DistrCode = id.DistrCode
                AND ih.InvoiceNo = id.InvoiceNo
                WHERE ih.DistrCode IN (:ids)
                GROUP BY ih.CmpCode, ih.DistrCode, ih.CustomerCode, id.ProdCode, ih.InvoiceDt
                ORDER BY ih.CmpCode, ih.DistrCode, ih.CustomerCode, id.ProdCode, ih.InvoiceDt DESC) src, (SELECT @row_number := 0, @str := '''') AS t
            ORDER BY CmpCode, DistrCode, CustomerCode, ProdCode, row_number DESC) temp
      WHERE temp.row_number <= 3
      GROUP BY CmpCode, DistrCode, CustomerCode, ProdCode) tmp
GROUP BY CmpCode, DistrCode, CustomerCode',
'',
'com.botree.interdbentity.model.CustomerStockEntity',
15,
null,
null,
null,
'Y',
'N',
0,
'24HRS');
