CREATE TABLE `dashboard_widget` (
  `CmpCode` varchar(10) NOT NULL,
  `DistrCode` varchar(50) NOT NULL,
  `CustomerCode` varchar(50) NOT NULL,
  `DisplayCode1` varchar(100) DEFAULT NULL,
  `DisplayValue1` varchar(100) DEFAULT NULL,
  `DisplayIcon1` varchar(50) DEFAULT NULL,
  `DisplayColor1` varchar(50) DEFAULT NULL,
  `DisplayCode2` varchar(100) DEFAULT NULL,
  `DisplayValue2` varchar(100) DEFAULT NULL,
  `DisplayIcon2` varchar(50) DEFAULT NULL,
  `DisplayColor2` varchar(50) DEFAULT NULL,
  `DisplayCode3` varchar(100) DEFAULT NULL,
  `DisplayValue3` varchar(100) DEFAULT NULL,
  `DisplayIcon3` varchar(50) DEFAULT NULL,
  `DisplayColor3` varchar(50) DEFAULT NULL,
  `DisplayCode4` varchar(100) DEFAULT NULL,
  `DisplayValue4` varchar(100) DEFAULT NULL,
  `DisplayIcon4` varchar(50) DEFAULT NULL,
  `DisplayColor4` varchar(50) DEFAULT NULL,
  `DisplayCode5` varchar(100) DEFAULT NULL,
  `DisplayValue5` varchar(100) DEFAULT NULL,
  `DisplayIcon5` varchar(50) DEFAULT NULL,
  `DisplayColor5` varchar(50) DEFAULT NULL,
  `DisplayCode6` varchar(100) DEFAULT NULL,
  `DisplayValue6` varchar(100) DEFAULT NULL,
  `DisplayIcon6` varchar(50) DEFAULT NULL,
  `DisplayColor6` varchar(50) DEFAULT NULL,
  `DisplayCode7` varchar(100) DEFAULT NULL,
  `DisplayValue7` varchar(100) DEFAULT NULL,
  `DisplayIcon7` varchar(50) DEFAULT NULL,
  `DisplayColor7` varchar(50) DEFAULT NULL,
  `DisplayCode8` varchar(100) DEFAULT NULL,
  `DisplayValue8` varchar(100) DEFAULT NULL,
  `DisplayIcon8` varchar(50) DEFAULT NULL,
  `DisplayColor8` varchar(50) DEFAULT NULL,
  `DisplayCode9` varchar(100) DEFAULT NULL,
  `DisplayValue9` varchar(100) DEFAULT NULL,
  `DisplayIcon9` varchar(50) DEFAULT NULL,
  `DisplayColor9` varchar(50) DEFAULT NULL,
  `DisplayCode10` varchar(100) DEFAULT NULL,
  `DisplayValue10` varchar(100) DEFAULT NULL,
  `DisplayIcon10` varchar(50) DEFAULT NULL,
  `DisplayColor10` varchar(50) DEFAULT NULL,
  `UploadFlag` char(1) NOT NULL DEFAULT 'N',
  `ModDt` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`CmpCode`,`DistrCode`,`CustomerCode`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `login_referral` (
  `CmpCode` varchar(10) NOT NULL,
  `DistrCode` varchar(50) NOT NULL,
  `SalesmanCode` varchar(50) NOT NULL,
  `CustomerCode` varchar(50) NOT NULL,
  `createdAt` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`CustomerCode`,`CmpCode`,`DistrCode`,`SalesmanCode`),
  KEY `cmp_code_fk_idx` (`CmpCode`,`DistrCode`,`SalesmanCode`),
  KEY `cmp_code_fk_login` (`CmpCode`,`DistrCode`,`SalesmanCode`),
  KEY `login_referral_salesman_index` (`CmpCode`,`DistrCode`,`SalesmanCode`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `order_referral` (
  `CmpCode` varchar(10) NOT NULL,
  `DistrCode` varchar(50) NOT NULL,
  `OrderNo` varchar(100) NOT NULL,
  `SalesmanCode` varchar(50) NOT NULL,
  `createdAt` datetime DEFAULT CURRENT_TIMESTAMP,
  `customerCode` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`DistrCode`,`CmpCode`,`OrderNo`,`SalesmanCode`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

