export enum SQLColumnType {
  INT = 'int',
  INT2 = 'int2',
  INT4 = 'int4',
  INT8 = 'int8',
  BIGINT = 'bigint',
  INTEGER = 'integer',
  TINY_INT = 'tinyint',
  SMALLINT = 'smallint',
  VARCHAR = 'varchar',
  BOOLEAN = 'boolean',
  CHAR = 'char',
  JSON = 'json',
  DATE_TIME = 'datetime',
}
